# Generated by Django 3.2.6 on 2021-08-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210824_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='daysLeft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
