# Generated by Django 3.2.6 on 2021-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_project_daysleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Unset', max_length=50),
        ),
    ]
