# Generated by Django 3.2.6 on 2021-08-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='daysLeft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(default='Unset', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='daysLeft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Unset', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_client',
            field=models.ForeignKey(blank=True, default='UNASSIGNED', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, default='UNASSIGNED', to='clients.Task'),
        ),
    ]
